// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_flexmetal

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func FlexmetalProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type FlexmetalModel struct {
}
