// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_flexvm_vm

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FlexvmVmResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cloud": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Computed:            true,
						Description:         "When the Cloud was created (RFC3339).",
						MarkdownDescription: "When the Cloud was created (RFC3339).",
					},
					"description": schema.StringAttribute{
						Computed:            true,
						Description:         "An optional free-form description of your Cloud.",
						MarkdownDescription: "An optional free-form description of your Cloud.",
					},
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Cloud UUID.",
						MarkdownDescription: "Cloud UUID.",
					},
					"instance_type": schema.StringAttribute{
						Computed:            true,
						Description:         "The FlexMetal instance type shared by every node in the Cloud.",
						MarkdownDescription: "The FlexMetal instance type shared by every node in the Cloud.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Cloud name.",
						MarkdownDescription: "Cloud name.",
					},
					"site": schema.StringAttribute{
						Computed:            true,
						Description:         "The i3D site (location) in which the Cloud is located. One of: frmtl1, camtr6.",
						MarkdownDescription: "The i3D site (location) in which the Cloud is located. One of: frmtl1, camtr6.",
					},
				},
				CustomType: CloudType{
					ObjectType: types.ObjectType{
						AttrTypes: CloudValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Cloud object within which the VM is deployed.",
				MarkdownDescription: "Cloud object within which the VM is deployed.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "VM creation timestamp.",
				MarkdownDescription: "VM creation timestamp.",
			},
			"deleted_at": schema.StringAttribute{
				Computed:            true,
				Description:         "VM deletion timestamp.",
				MarkdownDescription: "VM deletion timestamp.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "An optional free-form description of your VM.",
				MarkdownDescription: "An optional free-form description of your VM.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Cloud VM UUID.",
				MarkdownDescription: "Cloud VM UUID.",
			},
			"image": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Image name.",
						MarkdownDescription: "Image name.",
					},
					"os": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the OS that the image represents.",
						MarkdownDescription: "The name of the OS that the image represents.",
					},
					"os_type": schema.StringAttribute{
						Computed:            true,
						Description:         "The OS type the image represents. Can be \"linux\" or \"windows\"",
						MarkdownDescription: "The OS type the image represents. Can be \"linux\" or \"windows\"",
					},
				},
				CustomType: ImageType{
					ObjectType: types.ObjectType{
						AttrTypes: ImageValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The image the VM is based on.",
				MarkdownDescription: "The image the VM is based on.",
			},
			"image_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The image name to create the VM from.",
				MarkdownDescription: "The image name to create the VM from.",
			},
			"instance_type": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"disk": schema.Int64Attribute{
						Computed:            true,
						Description:         "The size of the OS disk in GB.",
						MarkdownDescription: "The size of the OS disk in GB.",
					},
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "FlexVM Instance Type UUID.",
						MarkdownDescription: "FlexVM Instance Type UUID.",
					},
					"memory": schema.Int64Attribute{
						Computed:            true,
						Description:         "The amount of memory in MB.",
						MarkdownDescription: "The amount of memory in MB.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the instance type.",
						MarkdownDescription: "The name of the instance type.",
					},
					"pci_devices": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"spec": schema.StringAttribute{
									Computed:            true,
									Description:         "A human-readable specification of the device (model, capacity, etc.).",
									MarkdownDescription: "A human-readable specification of the device (model, capacity, etc.).",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "The kind of pass-through device.<br /><li><ul>gpu</ul><ul>nvme</ul></li>",
									MarkdownDescription: "The kind of pass-through device.<br /><li><ul>gpu</ul><ul>nvme</ul></li>",
								},
							},
							CustomType: PciDevicesType{
								ObjectType: types.ObjectType{
									AttrTypes: PciDevicesValue{}.AttributeTypes(ctx),
								},
							},
						},
						Computed:            true,
						Description:         "PCI passthrough devices required by this instance type.",
						MarkdownDescription: "PCI passthrough devices required by this instance type.",
					},
					"vcpu": schema.Int64Attribute{
						Computed:            true,
						Description:         "The number of vCPU resources.",
						MarkdownDescription: "The number of vCPU resources.",
					},
				},
				CustomType: InstanceTypeType{
					ObjectType: types.ObjectType{
						AttrTypes: InstanceTypeValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The instance type the VM is based on.",
				MarkdownDescription: "The instance type the VM is based on.",
			},
			"instance_type_name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The instance type name to base the VM on.",
				MarkdownDescription: "The instance type name to base the VM on.",
			},
			"ips": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"address": schema.StringAttribute{
							Computed:            true,
							Description:         "An IP address, can be v4 or v6, public or private.",
							MarkdownDescription: "An IP address, can be v4 or v6, public or private.",
						},
						"public": schema.BoolAttribute{
							Computed:            true,
							Description:         "Indicates whether the IP address is a public or private one.",
							MarkdownDescription: "Indicates whether the IP address is a public or private one.",
						},
					},
					CustomType: IpsType{
						ObjectType: types.ObjectType{
							AttrTypes: IpsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "A list of IP address objects that belong to the VM.",
				MarkdownDescription: "A list of IP address objects that belong to the VM.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "VM name.",
				MarkdownDescription: "VM name.",
			},
			"node": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"cloud": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"created_at": schema.StringAttribute{
								Computed:            true,
								Description:         "When the Cloud was created (RFC3339).",
								MarkdownDescription: "When the Cloud was created (RFC3339).",
							},
							"description": schema.StringAttribute{
								Computed:            true,
								Description:         "An optional free-form description of your Cloud.",
								MarkdownDescription: "An optional free-form description of your Cloud.",
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "Cloud UUID.",
								MarkdownDescription: "Cloud UUID.",
							},
							"instance_type": schema.StringAttribute{
								Computed:            true,
								Description:         "The FlexMetal instance type shared by every node in the Cloud.",
								MarkdownDescription: "The FlexMetal instance type shared by every node in the Cloud.",
							},
							"name": schema.StringAttribute{
								Computed:            true,
								Description:         "Cloud name.",
								MarkdownDescription: "Cloud name.",
							},
							"site": schema.StringAttribute{
								Computed:            true,
								Description:         "The i3D site (location) in which the Cloud is located. One of: frmtl1, camtr6.",
								MarkdownDescription: "The i3D site (location) in which the Cloud is located. One of: frmtl1, camtr6.",
							},
						},
						CustomType: CloudType{
							ObjectType: types.ObjectType{
								AttrTypes: CloudValue{}.AttributeTypes(ctx),
							},
						},
						Computed:            true,
						Description:         "Cloud object to which the node belongs.",
						MarkdownDescription: "Cloud object to which the node belongs.",
					},
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Cloud Node UUID.",
						MarkdownDescription: "Cloud Node UUID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Cloud Node name.",
						MarkdownDescription: "Cloud Node name.",
					},
					"serial": schema.StringAttribute{
						Computed:            true,
						Description:         "Cloud Name serial number",
						MarkdownDescription: "Cloud Name serial number",
					},
				},
				CustomType: NodeType{
					ObjectType: types.ObjectType{
						AttrTypes: NodeValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Node object on which the VM is deployed.",
				MarkdownDescription: "Node object on which the VM is deployed.",
			},
			"ssh_keys": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Provide your public SSH key(s). Exactly one of ssh_keys or user_data must be specified: a request that sets both, or neither, is rejected with a 422. When user_data is provided instead, configure SSH access through it.",
				MarkdownDescription: "Provide your public SSH key(s). Exactly one of ssh_keys or user_data must be specified: a request that sets both, or neither, is rejected with a 422. When user_data is provided instead, configure SSH access through it.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The status of the VM.<br /><li><ul>provisioning</ul><ul>created</ul><ul>starting</ul><ul>running</ul><ul>stopping</ul><ul>stopped</ul><ul>paused</ul><ul>failed</ul><ul>deleting</ul><ul>deleted</ul></li>",
				MarkdownDescription: "The status of the VM.<br /><li><ul>provisioning</ul><ul>created</ul><ul>starting</ul><ul>running</ul><ul>stopping</ul><ul>stopped</ul><ul>paused</ul><ul>failed</ul><ul>deleting</ul><ul>deleted</ul></li>",
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "Free-form labels (e.g. project:odyssey, env:build) used for grouping in the monthly usage report. Set at VM create only — values must be non-empty strings up to 128 chars.",
				MarkdownDescription: "Free-form labels (e.g. project:odyssey, env:build) used for grouping in the monthly usage report. Set at VM create only — values must be non-empty strings up to 128 chars.",
			},
			"user_data": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"data": schema.StringAttribute{
						Required:            true,
						Description:         "Cloud-init user-data passed to the VM on first boot, in a format supported by cloud-init (e.g. a #cloud-config document or a shell script). May be base64-encoded when is_base64 is true. See the cloud-init supported user-data formats: https://docs.cloud-init.io/en/latest/explanation/format/index.html. Note: if provided, user-data overwrites the auto-generated cloud-init configuration which is responsible for configuring ssh-keys and the default username, for example. To ensure access, those must be configured by the provided user-data. Example configurations: https://docs.cloud-init.io/en/latest/reference/examples.html#yaml-examples. Length must be between 1 and 64000 characters.",
						MarkdownDescription: "Cloud-init user-data passed to the VM on first boot, in a format supported by cloud-init (e.g. a #cloud-config document or a shell script). May be base64-encoded when is_base64 is true. See the cloud-init supported user-data formats: https://docs.cloud-init.io/en/latest/explanation/format/index.html. Note: if provided, user-data overwrites the auto-generated cloud-init configuration which is responsible for configuring ssh-keys and the default username, for example. To ensure access, those must be configured by the provided user-data. Example configurations: https://docs.cloud-init.io/en/latest/reference/examples.html#yaml-examples. Length must be between 1 and 64000 characters.",
						Validators: []validator.String{
							stringvalidator.LengthBetween(1, 64000),
						},
					},
					"is_base64": schema.BoolAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Whether data is base64-encoded. Use this for binary user-data that cannot be encoded as JSON, such as gzip-compressed cloud-init content (e.g. https://docs.cloud-init.io/en/latest/explanation/format/gzip.html#gzip). Default is false.",
						MarkdownDescription: "Whether data is base64-encoded. Use this for binary user-data that cannot be encoded as JSON, such as gzip-compressed cloud-init content (e.g. https://docs.cloud-init.io/en/latest/explanation/format/gzip.html#gzip). Default is false.",
						Default:             booldefault.StaticBool(false),
					},
				},
				CustomType: UserDataType{
					ObjectType: types.ObjectType{
						AttrTypes: UserDataValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "Cloud-init user-data to pass to the VM on first boot. Exactly one of ssh_keys or user_data must be specified: a request that sets both, or neither, is rejected with a 422.",
				MarkdownDescription: "Cloud-init user-data to pass to the VM on first boot. Exactly one of ssh_keys or user_data must be specified: a request that sets both, or neither, is rejected with a 422.",
			},
		},
	}
}

type FlexvmVmModel struct {
	Cloud            CloudValue        `tfsdk:"cloud"`
	CreatedAt        types.String      `tfsdk:"created_at"`
	DeletedAt        types.String      `tfsdk:"deleted_at"`
	Description      types.String      `tfsdk:"description"`
	Id               types.String      `tfsdk:"id"`
	Image            ImageValue        `tfsdk:"image"`
	ImageName        types.String      `tfsdk:"image_name"`
	InstanceType     InstanceTypeValue `tfsdk:"instance_type"`
	InstanceTypeName types.String      `tfsdk:"instance_type_name"`
	Ips              types.List        `tfsdk:"ips"`
	Name             types.String      `tfsdk:"name"`
	Node             NodeValue         `tfsdk:"node"`
	SshKeys          types.List        `tfsdk:"ssh_keys"`
	Status           types.String      `tfsdk:"status"`
	Tags             types.List        `tfsdk:"tags"`
	UserData         UserDataValue     `tfsdk:"user_data"`
}

var _ basetypes.ObjectTypable = CloudType{}

type CloudType struct {
	basetypes.ObjectType
}

func (t CloudType) Equal(o attr.Type) bool {
	other, ok := o.(CloudType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CloudType) String() string {
	return "CloudType"
}

func (t CloudType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return nil, diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	instanceTypeAttribute, ok := attributes["instance_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance_type is missing from object`)

		return nil, diags
	}

	instanceTypeVal, ok := instanceTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance_type expected to be basetypes.StringValue, was: %T`, instanceTypeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	siteAttribute, ok := attributes["site"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site is missing from object`)

		return nil, diags
	}

	siteVal, ok := siteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site expected to be basetypes.StringValue, was: %T`, siteAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CloudValue{
		CreatedAt:    createdAtVal,
		Description:  descriptionVal,
		Id:           idVal,
		InstanceType: instanceTypeVal,
		Name:         nameVal,
		Site:         siteVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCloudValueNull() CloudValue {
	return CloudValue{
		state: attr.ValueStateNull,
	}
}

func NewCloudValueUnknown() CloudValue {
	return CloudValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCloudValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CloudValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CloudValue Attribute Value",
				"While creating a CloudValue value, a missing attribute value was detected. "+
					"A CloudValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CloudValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CloudValue Attribute Type",
				"While creating a CloudValue value, an invalid attribute value was detected. "+
					"A CloudValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CloudValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CloudValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CloudValue Attribute Value",
				"While creating a CloudValue value, an extra attribute value was detected. "+
					"A CloudValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CloudValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCloudValueUnknown(), diags
	}

	createdAtAttribute, ok := attributes["created_at"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created_at is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	createdAtVal, ok := createdAtAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created_at expected to be basetypes.StringValue, was: %T`, createdAtAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	instanceTypeAttribute, ok := attributes["instance_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`instance_type is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	instanceTypeVal, ok := instanceTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`instance_type expected to be basetypes.StringValue, was: %T`, instanceTypeAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	siteAttribute, ok := attributes["site"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`site is missing from object`)

		return NewCloudValueUnknown(), diags
	}

	siteVal, ok := siteAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`site expected to be basetypes.StringValue, was: %T`, siteAttribute))
	}

	if diags.HasError() {
		return NewCloudValueUnknown(), diags
	}

	return CloudValue{
		CreatedAt:    createdAtVal,
		Description:  descriptionVal,
		Id:           idVal,
		InstanceType: instanceTypeVal,
		Name:         nameVal,
		Site:         siteVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCloudValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CloudValue {
	object, diags := NewCloudValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCloudValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CloudType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCloudValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCloudValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCloudValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCloudValueMust(CloudValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CloudType) ValueType(ctx context.Context) attr.Value {
	return CloudValue{}
}

var _ basetypes.ObjectValuable = CloudValue{}

type CloudValue struct {
	CreatedAt    basetypes.StringValue `tfsdk:"created_at"`
	Description  basetypes.StringValue `tfsdk:"description"`
	Id           basetypes.StringValue `tfsdk:"id"`
	InstanceType basetypes.StringValue `tfsdk:"instance_type"`
	Name         basetypes.StringValue `tfsdk:"name"`
	Site         basetypes.StringValue `tfsdk:"site"`
	state        attr.ValueState
}

func (v CloudValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["created_at"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["instance_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["site"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.CreatedAt.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created_at"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.InstanceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["instance_type"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Site.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["site"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CloudValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CloudValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CloudValue) String() string {
	return "CloudValue"
}

func (v CloudValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"created_at":    basetypes.StringType{},
		"description":   basetypes.StringType{},
		"id":            basetypes.StringType{},
		"instance_type": basetypes.StringType{},
		"name":          basetypes.StringType{},
		"site":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"created_at":    v.CreatedAt,
			"description":   v.Description,
			"id":            v.Id,
			"instance_type": v.InstanceType,
			"name":          v.Name,
			"site":          v.Site,
		})

	return objVal, diags
}

func (v CloudValue) Equal(o attr.Value) bool {
	other, ok := o.(CloudValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CreatedAt.Equal(other.CreatedAt) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.InstanceType.Equal(other.InstanceType) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Site.Equal(other.Site) {
		return false
	}

	return true
}

func (v CloudValue) Type(ctx context.Context) attr.Type {
	return CloudType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CloudValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"created_at":    basetypes.StringType{},
		"description":   basetypes.StringType{},
		"id":            basetypes.StringType{},
		"instance_type": basetypes.StringType{},
		"name":          basetypes.StringType{},
		"site":          basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ImageType{}

type ImageType struct {
	basetypes.ObjectType
}

func (t ImageType) Equal(o attr.Type) bool {
	other, ok := o.(ImageType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ImageType) String() string {
	return "ImageType"
}

func (t ImageType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	osAttribute, ok := attributes["os"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os is missing from object`)

		return nil, diags
	}

	osVal, ok := osAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os expected to be basetypes.StringValue, was: %T`, osAttribute))
	}

	osTypeAttribute, ok := attributes["os_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_type is missing from object`)

		return nil, diags
	}

	osTypeVal, ok := osTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_type expected to be basetypes.StringValue, was: %T`, osTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ImageValue{
		Name:   nameVal,
		Os:     osVal,
		OsType: osTypeVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewImageValueNull() ImageValue {
	return ImageValue{
		state: attr.ValueStateNull,
	}
}

func NewImageValueUnknown() ImageValue {
	return ImageValue{
		state: attr.ValueStateUnknown,
	}
}

func NewImageValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ImageValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ImageValue Attribute Value",
				"While creating a ImageValue value, a missing attribute value was detected. "+
					"A ImageValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ImageValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ImageValue Attribute Type",
				"While creating a ImageValue value, an invalid attribute value was detected. "+
					"A ImageValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ImageValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ImageValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ImageValue Attribute Value",
				"While creating a ImageValue value, an extra attribute value was detected. "+
					"A ImageValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ImageValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewImageValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewImageValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	osAttribute, ok := attributes["os"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os is missing from object`)

		return NewImageValueUnknown(), diags
	}

	osVal, ok := osAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os expected to be basetypes.StringValue, was: %T`, osAttribute))
	}

	osTypeAttribute, ok := attributes["os_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`os_type is missing from object`)

		return NewImageValueUnknown(), diags
	}

	osTypeVal, ok := osTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`os_type expected to be basetypes.StringValue, was: %T`, osTypeAttribute))
	}

	if diags.HasError() {
		return NewImageValueUnknown(), diags
	}

	return ImageValue{
		Name:   nameVal,
		Os:     osVal,
		OsType: osTypeVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewImageValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ImageValue {
	object, diags := NewImageValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewImageValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ImageType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewImageValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewImageValueUnknown(), nil
	}

	if in.IsNull() {
		return NewImageValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewImageValueMust(ImageValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ImageType) ValueType(ctx context.Context) attr.Value {
	return ImageValue{}
}

var _ basetypes.ObjectValuable = ImageValue{}

type ImageValue struct {
	Name   basetypes.StringValue `tfsdk:"name"`
	Os     basetypes.StringValue `tfsdk:"os"`
	OsType basetypes.StringValue `tfsdk:"os_type"`
	state  attr.ValueState
}

func (v ImageValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["os"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["os_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Os.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os"] = val

		val, err = v.OsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["os_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ImageValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ImageValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ImageValue) String() string {
	return "ImageValue"
}

func (v ImageValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name":    basetypes.StringType{},
		"os":      basetypes.StringType{},
		"os_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":    v.Name,
			"os":      v.Os,
			"os_type": v.OsType,
		})

	return objVal, diags
}

func (v ImageValue) Equal(o attr.Value) bool {
	other, ok := o.(ImageValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Os.Equal(other.Os) {
		return false
	}

	if !v.OsType.Equal(other.OsType) {
		return false
	}

	return true
}

func (v ImageValue) Type(ctx context.Context) attr.Type {
	return ImageType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ImageValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name":    basetypes.StringType{},
		"os":      basetypes.StringType{},
		"os_type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = InstanceTypeType{}

type InstanceTypeType struct {
	basetypes.ObjectType
}

func (t InstanceTypeType) Equal(o attr.Type) bool {
	other, ok := o.(InstanceTypeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t InstanceTypeType) String() string {
	return "InstanceTypeType"
}

func (t InstanceTypeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	diskAttribute, ok := attributes["disk"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disk is missing from object`)

		return nil, diags
	}

	diskVal, ok := diskAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disk expected to be basetypes.Int64Value, was: %T`, diskAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	memoryAttribute, ok := attributes["memory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory is missing from object`)

		return nil, diags
	}

	memoryVal, ok := memoryAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory expected to be basetypes.Int64Value, was: %T`, memoryAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	pciDevicesAttribute, ok := attributes["pci_devices"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pci_devices is missing from object`)

		return nil, diags
	}

	pciDevicesVal, ok := pciDevicesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pci_devices expected to be basetypes.ListValue, was: %T`, pciDevicesAttribute))
	}

	vcpuAttribute, ok := attributes["vcpu"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu is missing from object`)

		return nil, diags
	}

	vcpuVal, ok := vcpuAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu expected to be basetypes.Int64Value, was: %T`, vcpuAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return InstanceTypeValue{
		Disk:       diskVal,
		Id:         idVal,
		Memory:     memoryVal,
		Name:       nameVal,
		PciDevices: pciDevicesVal,
		Vcpu:       vcpuVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewInstanceTypeValueNull() InstanceTypeValue {
	return InstanceTypeValue{
		state: attr.ValueStateNull,
	}
}

func NewInstanceTypeValueUnknown() InstanceTypeValue {
	return InstanceTypeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewInstanceTypeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (InstanceTypeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing InstanceTypeValue Attribute Value",
				"While creating a InstanceTypeValue value, a missing attribute value was detected. "+
					"A InstanceTypeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceTypeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid InstanceTypeValue Attribute Type",
				"While creating a InstanceTypeValue value, an invalid attribute value was detected. "+
					"A InstanceTypeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InstanceTypeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("InstanceTypeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra InstanceTypeValue Attribute Value",
				"While creating a InstanceTypeValue value, an extra attribute value was detected. "+
					"A InstanceTypeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra InstanceTypeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewInstanceTypeValueUnknown(), diags
	}

	diskAttribute, ok := attributes["disk"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disk is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	diskVal, ok := diskAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disk expected to be basetypes.Int64Value, was: %T`, diskAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	memoryAttribute, ok := attributes["memory"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	memoryVal, ok := memoryAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory expected to be basetypes.Int64Value, was: %T`, memoryAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	pciDevicesAttribute, ok := attributes["pci_devices"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`pci_devices is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	pciDevicesVal, ok := pciDevicesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`pci_devices expected to be basetypes.ListValue, was: %T`, pciDevicesAttribute))
	}

	vcpuAttribute, ok := attributes["vcpu"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu is missing from object`)

		return NewInstanceTypeValueUnknown(), diags
	}

	vcpuVal, ok := vcpuAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu expected to be basetypes.Int64Value, was: %T`, vcpuAttribute))
	}

	if diags.HasError() {
		return NewInstanceTypeValueUnknown(), diags
	}

	return InstanceTypeValue{
		Disk:       diskVal,
		Id:         idVal,
		Memory:     memoryVal,
		Name:       nameVal,
		PciDevices: pciDevicesVal,
		Vcpu:       vcpuVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewInstanceTypeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) InstanceTypeValue {
	object, diags := NewInstanceTypeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewInstanceTypeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t InstanceTypeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewInstanceTypeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewInstanceTypeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewInstanceTypeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewInstanceTypeValueMust(InstanceTypeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t InstanceTypeType) ValueType(ctx context.Context) attr.Value {
	return InstanceTypeValue{}
}

var _ basetypes.ObjectValuable = InstanceTypeValue{}

type InstanceTypeValue struct {
	Disk       basetypes.Int64Value  `tfsdk:"disk"`
	Id         basetypes.StringValue `tfsdk:"id"`
	Memory     basetypes.Int64Value  `tfsdk:"memory"`
	Name       basetypes.StringValue `tfsdk:"name"`
	PciDevices basetypes.ListValue   `tfsdk:"pci_devices"`
	Vcpu       basetypes.Int64Value  `tfsdk:"vcpu"`
	state      attr.ValueState
}

func (v InstanceTypeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["disk"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["memory"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["pci_devices"] = basetypes.ListType{
		ElemType: PciDevicesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["vcpu"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Disk.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disk"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Memory.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["memory"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.PciDevices.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["pci_devices"] = val

		val, err = v.Vcpu.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vcpu"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v InstanceTypeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v InstanceTypeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v InstanceTypeValue) String() string {
	return "InstanceTypeValue"
}

func (v InstanceTypeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	pciDevices := types.ListValueMust(
		PciDevicesType{
			basetypes.ObjectType{
				AttrTypes: PciDevicesValue{}.AttributeTypes(ctx),
			},
		},
		v.PciDevices.Elements(),
	)

	if v.PciDevices.IsNull() {
		pciDevices = types.ListNull(
			PciDevicesType{
				basetypes.ObjectType{
					AttrTypes: PciDevicesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.PciDevices.IsUnknown() {
		pciDevices = types.ListUnknown(
			PciDevicesType{
				basetypes.ObjectType{
					AttrTypes: PciDevicesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"disk":   basetypes.Int64Type{},
		"id":     basetypes.StringType{},
		"memory": basetypes.Int64Type{},
		"name":   basetypes.StringType{},
		"pci_devices": basetypes.ListType{
			ElemType: PciDevicesValue{}.Type(ctx),
		},
		"vcpu": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"disk":        v.Disk,
			"id":          v.Id,
			"memory":      v.Memory,
			"name":        v.Name,
			"pci_devices": pciDevices,
			"vcpu":        v.Vcpu,
		})

	return objVal, diags
}

func (v InstanceTypeValue) Equal(o attr.Value) bool {
	other, ok := o.(InstanceTypeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Disk.Equal(other.Disk) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Memory.Equal(other.Memory) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.PciDevices.Equal(other.PciDevices) {
		return false
	}

	if !v.Vcpu.Equal(other.Vcpu) {
		return false
	}

	return true
}

func (v InstanceTypeValue) Type(ctx context.Context) attr.Type {
	return InstanceTypeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v InstanceTypeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"disk":   basetypes.Int64Type{},
		"id":     basetypes.StringType{},
		"memory": basetypes.Int64Type{},
		"name":   basetypes.StringType{},
		"pci_devices": basetypes.ListType{
			ElemType: PciDevicesValue{}.Type(ctx),
		},
		"vcpu": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = PciDevicesType{}

type PciDevicesType struct {
	basetypes.ObjectType
}

func (t PciDevicesType) Equal(o attr.Type) bool {
	other, ok := o.(PciDevicesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PciDevicesType) String() string {
	return "PciDevicesType"
}

func (t PciDevicesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	specAttribute, ok := attributes["spec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`spec is missing from object`)

		return nil, diags
	}

	specVal, ok := specAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`spec expected to be basetypes.StringValue, was: %T`, specAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PciDevicesValue{
		Spec:           specVal,
		PciDevicesType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewPciDevicesValueNull() PciDevicesValue {
	return PciDevicesValue{
		state: attr.ValueStateNull,
	}
}

func NewPciDevicesValueUnknown() PciDevicesValue {
	return PciDevicesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPciDevicesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PciDevicesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PciDevicesValue Attribute Value",
				"While creating a PciDevicesValue value, a missing attribute value was detected. "+
					"A PciDevicesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PciDevicesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PciDevicesValue Attribute Type",
				"While creating a PciDevicesValue value, an invalid attribute value was detected. "+
					"A PciDevicesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PciDevicesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PciDevicesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PciDevicesValue Attribute Value",
				"While creating a PciDevicesValue value, an extra attribute value was detected. "+
					"A PciDevicesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PciDevicesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPciDevicesValueUnknown(), diags
	}

	specAttribute, ok := attributes["spec"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`spec is missing from object`)

		return NewPciDevicesValueUnknown(), diags
	}

	specVal, ok := specAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`spec expected to be basetypes.StringValue, was: %T`, specAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewPciDevicesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewPciDevicesValueUnknown(), diags
	}

	return PciDevicesValue{
		Spec:           specVal,
		PciDevicesType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewPciDevicesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PciDevicesValue {
	object, diags := NewPciDevicesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPciDevicesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PciDevicesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPciDevicesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPciDevicesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPciDevicesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPciDevicesValueMust(PciDevicesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PciDevicesType) ValueType(ctx context.Context) attr.Value {
	return PciDevicesValue{}
}

var _ basetypes.ObjectValuable = PciDevicesValue{}

type PciDevicesValue struct {
	Spec           basetypes.StringValue `tfsdk:"spec"`
	PciDevicesType basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v PciDevicesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["spec"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Spec.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["spec"] = val

		val, err = v.PciDevicesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PciDevicesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PciDevicesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PciDevicesValue) String() string {
	return "PciDevicesValue"
}

func (v PciDevicesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"spec": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"spec": v.Spec,
			"type": v.PciDevicesType,
		})

	return objVal, diags
}

func (v PciDevicesValue) Equal(o attr.Value) bool {
	other, ok := o.(PciDevicesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Spec.Equal(other.Spec) {
		return false
	}

	if !v.PciDevicesType.Equal(other.PciDevicesType) {
		return false
	}

	return true
}

func (v PciDevicesValue) Type(ctx context.Context) attr.Type {
	return PciDevicesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PciDevicesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"spec": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = IpsType{}

type IpsType struct {
	basetypes.ObjectType
}

func (t IpsType) Equal(o attr.Type) bool {
	other, ok := o.(IpsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t IpsType) String() string {
	return "IpsType"
}

func (t IpsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	addressAttribute, ok := attributes["address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`address is missing from object`)

		return nil, diags
	}

	addressVal, ok := addressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`address expected to be basetypes.StringValue, was: %T`, addressAttribute))
	}

	publicAttribute, ok := attributes["public"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public is missing from object`)

		return nil, diags
	}

	publicVal, ok := publicAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public expected to be basetypes.BoolValue, was: %T`, publicAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return IpsValue{
		Address: addressVal,
		Public:  publicVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewIpsValueNull() IpsValue {
	return IpsValue{
		state: attr.ValueStateNull,
	}
}

func NewIpsValueUnknown() IpsValue {
	return IpsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewIpsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (IpsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing IpsValue Attribute Value",
				"While creating a IpsValue value, a missing attribute value was detected. "+
					"A IpsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid IpsValue Attribute Type",
				"While creating a IpsValue value, an invalid attribute value was detected. "+
					"A IpsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("IpsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("IpsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra IpsValue Attribute Value",
				"While creating a IpsValue value, an extra attribute value was detected. "+
					"A IpsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra IpsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewIpsValueUnknown(), diags
	}

	addressAttribute, ok := attributes["address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`address is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	addressVal, ok := addressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`address expected to be basetypes.StringValue, was: %T`, addressAttribute))
	}

	publicAttribute, ok := attributes["public"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`public is missing from object`)

		return NewIpsValueUnknown(), diags
	}

	publicVal, ok := publicAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`public expected to be basetypes.BoolValue, was: %T`, publicAttribute))
	}

	if diags.HasError() {
		return NewIpsValueUnknown(), diags
	}

	return IpsValue{
		Address: addressVal,
		Public:  publicVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewIpsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) IpsValue {
	object, diags := NewIpsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewIpsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t IpsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewIpsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewIpsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewIpsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewIpsValueMust(IpsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t IpsType) ValueType(ctx context.Context) attr.Value {
	return IpsValue{}
}

var _ basetypes.ObjectValuable = IpsValue{}

type IpsValue struct {
	Address basetypes.StringValue `tfsdk:"address"`
	Public  basetypes.BoolValue   `tfsdk:"public"`
	state   attr.ValueState
}

func (v IpsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["public"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Address.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["address"] = val

		val, err = v.Public.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["public"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v IpsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v IpsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v IpsValue) String() string {
	return "IpsValue"
}

func (v IpsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"address": basetypes.StringType{},
		"public":  basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"address": v.Address,
			"public":  v.Public,
		})

	return objVal, diags
}

func (v IpsValue) Equal(o attr.Value) bool {
	other, ok := o.(IpsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Address.Equal(other.Address) {
		return false
	}

	if !v.Public.Equal(other.Public) {
		return false
	}

	return true
}

func (v IpsValue) Type(ctx context.Context) attr.Type {
	return IpsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v IpsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"address": basetypes.StringType{},
		"public":  basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = NodeType{}

type NodeType struct {
	basetypes.ObjectType
}

func (t NodeType) Equal(o attr.Type) bool {
	other, ok := o.(NodeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodeType) String() string {
	return "NodeType"
}

func (t NodeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cloudAttribute, ok := attributes["cloud"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud is missing from object`)

		return nil, diags
	}

	cloudVal, ok := cloudAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud expected to be basetypes.ObjectValue, was: %T`, cloudAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	serialAttribute, ok := attributes["serial"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`serial is missing from object`)

		return nil, diags
	}

	serialVal, ok := serialAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`serial expected to be basetypes.StringValue, was: %T`, serialAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodeValue{
		Cloud:  cloudVal,
		Id:     idVal,
		Name:   nameVal,
		Serial: serialVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewNodeValueNull() NodeValue {
	return NodeValue{
		state: attr.ValueStateNull,
	}
}

func NewNodeValueUnknown() NodeValue {
	return NodeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodeValue Attribute Value",
				"While creating a NodeValue value, a missing attribute value was detected. "+
					"A NodeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodeValue Attribute Type",
				"While creating a NodeValue value, an invalid attribute value was detected. "+
					"A NodeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodeValue Attribute Value",
				"While creating a NodeValue value, an extra attribute value was detected. "+
					"A NodeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodeValueUnknown(), diags
	}

	cloudAttribute, ok := attributes["cloud"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cloud is missing from object`)

		return NewNodeValueUnknown(), diags
	}

	cloudVal, ok := cloudAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cloud expected to be basetypes.ObjectValue, was: %T`, cloudAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodeValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewNodeValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	serialAttribute, ok := attributes["serial"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`serial is missing from object`)

		return NewNodeValueUnknown(), diags
	}

	serialVal, ok := serialAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`serial expected to be basetypes.StringValue, was: %T`, serialAttribute))
	}

	if diags.HasError() {
		return NewNodeValueUnknown(), diags
	}

	return NodeValue{
		Cloud:  cloudVal,
		Id:     idVal,
		Name:   nameVal,
		Serial: serialVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewNodeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodeValue {
	object, diags := NewNodeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodeValueMust(NodeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodeType) ValueType(ctx context.Context) attr.Value {
	return NodeValue{}
}

var _ basetypes.ObjectValuable = NodeValue{}

type NodeValue struct {
	Cloud  basetypes.ObjectValue `tfsdk:"cloud"`
	Id     basetypes.StringValue `tfsdk:"id"`
	Name   basetypes.StringValue `tfsdk:"name"`
	Serial basetypes.StringValue `tfsdk:"serial"`
	state  attr.ValueState
}

func (v NodeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["cloud"] = basetypes.ObjectType{
		AttrTypes: CloudValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["serial"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.Cloud.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cloud"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Serial.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["serial"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodeValue) String() string {
	return "NodeValue"
}

func (v NodeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var cloud basetypes.ObjectValue

	if v.Cloud.IsNull() {
		cloud = types.ObjectNull(
			CloudValue{}.AttributeTypes(ctx),
		)
	}

	if v.Cloud.IsUnknown() {
		cloud = types.ObjectUnknown(
			CloudValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Cloud.IsNull() && !v.Cloud.IsUnknown() {
		cloud = types.ObjectValueMust(
			CloudValue{}.AttributeTypes(ctx),
			v.Cloud.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"cloud": basetypes.ObjectType{
			AttrTypes: CloudValue{}.AttributeTypes(ctx),
		},
		"id":     basetypes.StringType{},
		"name":   basetypes.StringType{},
		"serial": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"cloud":  cloud,
			"id":     v.Id,
			"name":   v.Name,
			"serial": v.Serial,
		})

	return objVal, diags
}

func (v NodeValue) Equal(o attr.Value) bool {
	other, ok := o.(NodeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Cloud.Equal(other.Cloud) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Serial.Equal(other.Serial) {
		return false
	}

	return true
}

func (v NodeValue) Type(ctx context.Context) attr.Type {
	return NodeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"cloud": basetypes.ObjectType{
			AttrTypes: CloudValue{}.AttributeTypes(ctx),
		},
		"id":     basetypes.StringType{},
		"name":   basetypes.StringType{},
		"serial": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = UserDataType{}

type UserDataType struct {
	basetypes.ObjectType
}

func (t UserDataType) Equal(o attr.Type) bool {
	other, ok := o.(UserDataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t UserDataType) String() string {
	return "UserDataType"
}

func (t UserDataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	dataAttribute, ok := attributes["data"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data is missing from object`)

		return nil, diags
	}

	dataVal, ok := dataAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data expected to be basetypes.StringValue, was: %T`, dataAttribute))
	}

	isBase64Attribute, ok := attributes["is_base64"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_base64 is missing from object`)

		return nil, diags
	}

	isBase64Val, ok := isBase64Attribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_base64 expected to be basetypes.BoolValue, was: %T`, isBase64Attribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return UserDataValue{
		Data:     dataVal,
		IsBase64: isBase64Val,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewUserDataValueNull() UserDataValue {
	return UserDataValue{
		state: attr.ValueStateNull,
	}
}

func NewUserDataValueUnknown() UserDataValue {
	return UserDataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewUserDataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (UserDataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing UserDataValue Attribute Value",
				"While creating a UserDataValue value, a missing attribute value was detected. "+
					"A UserDataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserDataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid UserDataValue Attribute Type",
				"While creating a UserDataValue value, an invalid attribute value was detected. "+
					"A UserDataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("UserDataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("UserDataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra UserDataValue Attribute Value",
				"While creating a UserDataValue value, an extra attribute value was detected. "+
					"A UserDataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra UserDataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewUserDataValueUnknown(), diags
	}

	dataAttribute, ok := attributes["data"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`data is missing from object`)

		return NewUserDataValueUnknown(), diags
	}

	dataVal, ok := dataAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`data expected to be basetypes.StringValue, was: %T`, dataAttribute))
	}

	isBase64Attribute, ok := attributes["is_base64"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_base64 is missing from object`)

		return NewUserDataValueUnknown(), diags
	}

	isBase64Val, ok := isBase64Attribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_base64 expected to be basetypes.BoolValue, was: %T`, isBase64Attribute))
	}

	if diags.HasError() {
		return NewUserDataValueUnknown(), diags
	}

	return UserDataValue{
		Data:     dataVal,
		IsBase64: isBase64Val,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewUserDataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) UserDataValue {
	object, diags := NewUserDataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewUserDataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t UserDataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewUserDataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewUserDataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewUserDataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewUserDataValueMust(UserDataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t UserDataType) ValueType(ctx context.Context) attr.Value {
	return UserDataValue{}
}

var _ basetypes.ObjectValuable = UserDataValue{}

type UserDataValue struct {
	Data     basetypes.StringValue `tfsdk:"data"`
	IsBase64 basetypes.BoolValue   `tfsdk:"is_base64"`
	state    attr.ValueState
}

func (v UserDataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["data"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["is_base64"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Data.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["data"] = val

		val, err = v.IsBase64.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_base64"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v UserDataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v UserDataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v UserDataValue) String() string {
	return "UserDataValue"
}

func (v UserDataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"data":      basetypes.StringType{},
		"is_base64": basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"data":      v.Data,
			"is_base64": v.IsBase64,
		})

	return objVal, diags
}

func (v UserDataValue) Equal(o attr.Value) bool {
	other, ok := o.(UserDataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Data.Equal(other.Data) {
		return false
	}

	if !v.IsBase64.Equal(other.IsBase64) {
		return false
	}

	return true
}

func (v UserDataValue) Type(ctx context.Context) attr.Type {
	return UserDataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v UserDataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"data":      basetypes.StringType{},
		"is_base64": basetypes.BoolType{},
	}
}
