// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_i3dnet

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func I3dnetProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type I3dnetModel struct {
}
